version: '3.8'

services:
  api:
    build: . 
    container_name: recipe_api
    network_mode: host
    command: python3 src/main.py
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:14.7-alpine
    container_name: db_posgresql
    env_file: .env
    ports:
      - "5432:5432"
